# frozen_string_literal: true

require "test_helper"
require "tmpdir"
require "fileutils"
require "exhale/source_files"

class SourceFilesTest < Minitest::Test
  KEPT = {
    "app/models/user.rb" => "class User; end\n",
    "app/views/users/show.html.erb" => "<p>hi</p>\n",
    "app/views/users/show.turbo_stream.erb" => "<p>hi</p>\n",
    "lib/tasks/thing.rb" => "x = 1\n",
    "a.rb" => "a\n",
    "app/models/bad.rb" => "x = \"\xFF\xFE\"\n".b
  }.freeze

  EXCLUDED = {
    "db/schema.rb" => "x\n",
    "config/routes.rb" => "x\n",
    "vendor/gem/a.rb" => "x\n",
    "node_modules/p/a.rb" => "x\n",
    "tmp/a.rb" => "x\n",
    "log/a.rb" => "x\n",
    "coverage/a.rb" => "x\n",
    "public/a.rb" => "x\n",
    "storage/a.rb" => "x\n",
    "bin/setup.rb" => "x\n",
    "app/assets/builds/a.rb" => "x\n",
    ".bundle/a.rb" => "x\n",
    "app/.hidden/a.rb" => "x\n",
    "app/models/readme.md" => "x\n",
    "app/cells/agent/prompt.erb" => "Summarize <url>\n",
    "app/views/users/show.json.erb" => "{}\n",
    "app/models/gen.rb" => "# frozen\n# Auto-generated by tool\nx\n",
    "app/models/gen2.rb" => "# DO NOT EDIT\nx\n"
  }.freeze

  TESTS = {
    "test/models/user_test.rb" => "x\n",
    "spec/models/user_spec.rb" => "x\n",
    "app/spec/helper.rb" => "x\n",
    "lib/foo/test/helper.rb" => "x\n",
    "lib/foo_test.rb" => "x\n",
    "lib/foo_spec.rb" => "x\n"
  }.freeze

  def setup
    @root = Dir.mktmpdir("exhale-src")
    [KEPT, EXCLUDED, TESTS].each do |set|
      set.each do |path, content|
        full = File.join(@root, path)
        FileUtils.mkdir_p(File.dirname(full))
        File.binwrite(full, content)
      end
    end
  end

  def teardown
    FileUtils.remove_entry(@root)
  end

  # Contract: source/S1
  # Contract: source/S2
  # Contract: source/S3
  # Contract: source/S4
  def test_walks_and_excludes
    result = Exhale::SourceFiles.list(@root)
    assert_equal KEPT.keys.sort, result.map(&:first)
  end

  # Value: protects=a path under a directory whose name starts with a dot is left out even when git lists it; fails_when=only the directory walk skips dot directories, so tracked files under .github or app/.hidden are compared; why_new=the dot-directory fixtures were only ever walked, and the walk skips dot paths itself; seam=none
  # Contract: source/S2
  def test_dot_directories_are_excluded_from_a_git_file_list_too
    files = [".bundle/a.rb", "app/.hidden/a.rb", "app/models/user.rb"]

    assert_equal ["app/models/user.rb"], Exhale::SourceFiles.list(@root, files: files).map(&:first)
  end

  # Contract: source/S1
  def test_languages
    result = Exhale::SourceFiles.list(@root).to_h
    assert_equal :ruby, result["app/models/user.rb"]
    assert_equal :erb, result["app/views/users/show.html.erb"]
    assert_equal :erb, result["app/views/users/show.turbo_stream.erb"]
  end

  # Contract: source/S3
  def test_include_tests
    paths = Exhale::SourceFiles.list(@root, include_tests: true).map(&:first)
    assert_equal (KEPT.keys + TESTS.keys).sort, paths
  end

  # Contract: source/S6
  def test_files_filter
    files = ["app/models/user.rb", "db/schema.rb", "app/models/readme.md", "zzz/missing.rb", "a.rb"]
    result = Exhale::SourceFiles.list(@root, files: files)
    assert_equal [["a.rb", :ruby], ["app/models/user.rb", :ruby]], result
  end

  # Contract: source/S4
  def test_generated_header_only_in_first_five_lines
    File.write(File.join(@root, "late.rb"), "1\n2\n3\n4\n5\n# generated by x\n")
    assert_includes Exhale::SourceFiles.list(@root).map(&:first), "late.rb"
  end

  # Value: protects=an empty file has no header, so it stays on the list instead of stopping the run; fails_when=the header check modifies the frozen string an empty read gives and raises FrozenError (issue #14); why_new=no fixture was empty; seam=none
  # Contract: source/S4
  def test_an_empty_file_has_no_header_and_stays_listed
    File.binwrite(File.join(@root, "app/models/empty.rb"), "")
    File.binwrite(File.join(@root, "app/views/users/empty.html.erb"), "")

    listed = Exhale::SourceFiles.list(@root).map(&:first)

    assert_includes listed, "app/models/empty.rb"
    assert_includes listed, "app/views/users/empty.html.erb"
  end

  # Contract: unit/U9
  def test_unreadable_file_stays_listed_for_the_sweep_to_report
    path = File.join(@root, "locked.rb")
    File.write(path, "x\n")
    File.chmod(0o000, path)
    assert_includes Exhale::SourceFiles.list(@root).map(&:first), "locked.rb"
    assert_includes Exhale::SourceFiles.list(@root, files: ["locked.rb"]).map(&:first), "locked.rb"
  ensure
    File.chmod(0o644, path) if path && File.exist?(path)
  end

  # Contract: unit/U9
  def test_invalid_utf8_file_stays_listed_for_the_sweep_to_report
    assert_equal [["app/models/bad.rb", :ruby]], Exhale::SourceFiles.list(@root, files: ["app/models/bad.rb"])
  end

  # Contract: source/S6
  def test_a_listed_file_missing_from_disk_is_dropped
    assert_empty Exhale::SourceFiles.list(@root, files: ["app/models/deleted.rb"])
  end

  # Contract: source/S4
  def test_generated_means_a_header_comment_that_opens_with_the_marker
    skipped = {
      "app/models/g1.rb" => "# This file is auto-generated from schema.yml\nx\n",
      "app/models/g2.rb" => "# frozen_string_literal: true\n# Code generated by protoc. DO NOT EDIT.\nx\n",
      "app/models/g3.rb" => "# Generated by rake build, DO NOT EDIT\nx\n",
      "app/models/g4.rb" => "   # This file is automatically generated\nx\n",
      "app/views/g/a.html.erb" => "<%# Auto-generated by tailwind %>\n<p></p>\n",
      "app/models/g5.rb" => "// DO NOT EDIT\nx\n"
    }
    kept = {
      "app/models/k1.rb" => "# Compares against the same auto-generated snapshot the importer writes.\nx\n",
      "app/models/k2.rb" => "# Generated by hand from the spec\nx\n",
      "app/models/k3.rb" => "WARNING = \"DO NOT EDIT\"\n",
      "app/models/k4.rb" => "# Please do not edit the importer without asking\nx\n"
    }
    skipped.merge(kept).each { |file, content| write(file, content) }
    listed = Exhale::SourceFiles.list(@root).map(&:first)

    skipped.each_key { |file| refute_includes listed, file }
    kept.each_key { |file| assert_includes listed, file }
  end

  # Contract: source/S2
  def test_db_and_config_are_excluded_at_the_root_and_one_level_under_monorepo_dirs
    excluded = %w[engines/billing/db/migrate/1_x.rb packs/billing/config/routes.rb components/a/db/seeds.rb
                  gems/tool/config/x.rb]
    kept = %w[engines/billing/app/models/a.rb app/models/config/x.rb lib/db/x.rb engines/a/b/db/x.rb]
    (excluded + kept).each { |file| write(file, "x\n") }
    listed = Exhale::SourceFiles.list(@root).map(&:first)

    excluded.each { |file| refute_includes listed, file }
    kept.each { |file| assert_includes listed, file }
  end

  # Contract: source/S5
  def test_symlinks_are_skipped_in_the_walk_and_the_files_filter
    File.symlink(File.join(@root, "app/models/user.rb"), File.join(@root, "app/models/alias.rb"))
    File.symlink(File.join(@root, "app/models"), File.join(@root, "app/shared"))
    files = ["app/models/alias.rb", "app/shared/user.rb", "app/models/user.rb"]

    refute_includes Exhale::SourceFiles.walk(@root), "app/models/alias.rb"
    refute_includes Exhale::SourceFiles.list(@root).map(&:first), "app/models/alias.rb"
    assert_equal [["app/models/user.rb", :ruby]], Exhale::SourceFiles.list(@root, files: files)
  end

  private

  def write(path, content)
    full = File.join(@root, path)
    FileUtils.mkdir_p(File.dirname(full))
    File.binwrite(full, content)
  end
end
